### PR TITLE
Feature/scroll to top button

### PR DESCRIPTION
**Pull request by beboptank**
I believe I'm headed in the right direction after a lot of googling and studying, I feel like a baby deer with react. Still working styling, to be pushed later

### CODE REVIEW

**Comment by Saggitarie** [comment]
Great effort you've put there! Keep it up!

As @dastrong  commented above, it is probably a good idea to change your component to functional component. This is because the internal state of scroll-to-top button doesn't really change. Therefore, they don't really care about lifecycle components.

Also, I'll advice you to be careful of which branch you're trying to merge this branch to. I think the client branch has been merged into the master branch a while ago. Why don't you request for merging into the master branch instead?

**Comment by dastrong** [comment]
Yup, @Saggitarie is right.

This should be merged into master.

**Comment by beboptank** [comment]
My mistake, will merge into master

**Comment by dastrong** [comment]
Thanks for updating.

**Pull request merged**
