### PR TITLE
Dev settings/css architecture

### PR DESCRIPTION
**Pull request by Saggitarie**
### Purpose
I was successfully able to implement the 7-1 architecture to our project. 

### Overview
I've been searching on how to implement this 7-1 architecture for our project on Nextjs for a while.
It seems like it works just by setting the path of the file (in our case "main.scss") for our globalSass variable. (I have no idea why it didn't worked 2 days ago... but NVM it works now haha)

### What to expect from this update
We can place all sass file inside the sass directory now! Yeah :)
Therefore, we don't have to write any imports inside our components for styling, since Nextjs will probably automatically read main.scss, in which adds all CSS file to the HTML file.

### References
Visit the guideline to learn more about [Sass](https://sass-guidelin.es/).
It gives an explanation about 7-1 architecture as well.

### CODE REVIEW

**Comment by Saggitarie** [comment]
@dastrong 
Thanks for your feedback.

I understood first part of your explanation about reducing the @import statement.
However, I don't quite understand the latter part.

So are you saying that we should do the following?

1) next.config.js
`const globalSass = ["sass/_abstract.scss"]; `

2) main.scss
Just @import _abstract.scss

3) /sass/abstract
Put all files inside this directory.

4) app.js
`import '../sass/main.scss`

** But if we do this (especially 3), I believe there will no meaning of 7-1 architecture **

**Comment by dastrong** [comment]
> 1. next.config.js
>    `const globalSass = ["sass/_abstract.scss"]; `
> 2. main.scss
>    Just @import _abstract.scss
> 3. /sass/abstract
>    Put all files inside this directory.
> 4. app.js
>    `import '../sass/main.scss`

1. next.config.js
`const globalSass = ["sass/_variables.scss", "sass/_mixins.scss", "sass/_functions.scss"]; `

2. main.scss
you could remove the three files above, because globalSass will import them everywhere for you

3. No, leave this as is

4. Yes, make that change

Then when you're in a component's scss file you won't need to do this `@import _variables.scss`, if you want to use some of those variables. Since 1 above will make them global.

**Comment by Saggitarie** [comment]
@dastrong
All right. I’ll fix this

**Comment by Saggitarie** [comment]
Done fixing it. 
If it seems okay, then you can merge this branch to the master branch.

@beboptank  Please apply this architecture for your components as well, before merging them into the master branch. Thanks!!

**Comment by dastrong** [comment]
Sorry, I thought I already merged this.

**Pull request merged**
