### PR TITLE
SortView - finished

### PR DESCRIPTION
**Pull request by Saggitarie**
### Overview

Working on Sortview component. I am almost finished with this component, but I am still struggling with the CSS styling for the react select. 

スクリーンショット 2019-12-11 17 14 40

1) I want the width for the this select item to be fixed. However, it changes depending on the word length of the option selected.

2) I also want the icon and the label to be in the single line. 

I kind of need help here.

### CODE REVIEW

**Comment by dastrong** [comment]
1) Reddit doesn't seem to use a fixed width, so I'd avoid adding one. If you think it looks best tho...
```jsx
const customStyles = {
  // I believe the element you're trying to target is - control
  // Inspect the elements in your browser to make sure tho
  // Possible elements keys are listed here: https://react-select.com/styles#style-object
  control: (reactSelectStyles, selectState) => ({
   ...reactSelectStyles, // omit if you don't want any of the React-Select style for this component
    width: 120;
  })
}

<Select 
  styles={customStyles}
/>
```
> [Link to docs](https://react-select.com/styles#provided-styles-and-state)

2) To align the items, I just make the container around the icon and text this:
```css
display: flex;
align-items: center;
```

**Comment by dastrong** [comment]
@Saggitarie I got a bunch of `React-Select` work in the last two days, so let me know if you need any further help on this.

**Comment by Saggitarie** [comment]
Almost there, but can't get the css right for react select....

Do you guys have any idea what I'm doing wrong?

**Comment by dastrong** [comment]
@Saggitarie - An overview of what was done:
- made the component names (in file) PascalCase'd
- removed `png` image and inserted `svg` image
  - copied these `svg`'s directly from reddit
- edited class names, so the `.sass` file could cascade (di
  - did these for readability and to avoid conflicting css later on
- I edited the folder/file structure a couple times
  - the naming convention is different in this folder, since `SortView` is really two components together
  - `SortViewSort` is weird, so I kept it the same and refactored `react-select` components down into their own `customblah` files

Now you were having issues styling the `Select`. Ultimately, I chose to style with a SASS file and the `React-Select` styles API (you view these in the `/customStyles.js` file). 
- If I could reach a `React-Select` component through their API (things like their `menu`, `menuList`, or `control` components), I would edit the CSS there.
- If I couldn't (things like our `customValueContainer` or `customOption`), I would do it in the SASS file.

**Comment by Saggitarie** [comment]
Thanks for the fix @dastrong 

Looked at the styles and it looks great!!

Will merge this

**Pull request merged**
